on:
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Hadolint
      uses: hadolint/hadolint-action@v3.1.0
